# Session 2: Python

By **Paul Rognon & Miquel Torrens i Dinarès & Maxim Fedotov**

*Barcelona School of Economics* –
*Data Science Center*

October 27th, 2022

---
## Modules and imports

*Modules* are `python` files, recognised in the computer as `<filename>.py`. Data and methods defined in the module can become part of the namespace by using `import`.

In [2]:
x = sin(5)  # The "sin" function does not exist

NameError: ignored

In [3]:
from math import sin  # You need to "import" it
x = sin(5)
print(x)

-0.9589242746631385


There are some other useful tricks to import data and methods:

In [4]:
from math import sin  # Imports a single function
from math import sin as sinus  # Nickname, useful when you import something with a long name
print(sinus(3))

import math  # Imports the module in the namespace, methods can then be accessed e.g.
print(math.sin(3))

0.1411200080598672
0.1411200080598672


Let us discuss here a couple of fundamental imports in `python`:

### `numpy` (Numerical Python)

*   User's manual: https://numpy.org/doc/stable/

This is Python's stack for scientific computing. The fundamental new data type is that of a **`numpy` `array`**, Python's matrix-type object, which is used in the majority of its data analysis, statistics and machine learning modules.

These arrays contain data that must all be of the same type (dtype):

In [5]:
# Import module 
import numpy as np  # usually imported with name "np"

# Creating an array
A = np.array([[1, 2, 3, 4, 5, 6], 
              [42, 53, 43 ,62, 7, 4], 
              [-3, -1, -4 ,-8, -52, -4], 
              [10, 0, 4 , 1, 0, 1]])
print(A)
print(A.dtype)

[[  1   2   3   4   5   6]
 [ 42  53  43  62   7   4]
 [ -3  -1  -4  -8 -52  -4]
 [ 10   0   4   1   0   1]]
int64


We can access the elements in an array using multi-index notation (counting starts from 0, slicing `a:b` is inclusive:exclusive, negative indices, etc.)

In [6]:
print(A)
# Print from row 3 onwards, columns 3 and 5
print(A[2:, [2, 4]])

[[  1   2   3   4   5   6]
 [ 42  53  43  62   7   4]
 [ -3  -1  -4  -8 -52  -4]
 [ 10   0   4   1   0   1]]
[[ -4 -52]
 [  4   0]]


In [7]:
# Attributes
A.shape  # dimension
A.min()  # minimum (you can similarly use max, sum, etc.)
A.diagonal()  # diagonal
B = A.transpose()  # transposing
C = A.reshape(6, 4)  # rearrange values to change dimension (CAREFUL!)
print(A.shape)
print(B.shape)
print(C.shape)
A.dot(B)  # dot-product (with array B)


(4, 6)
(6, 4)
(6, 4)


array([[   91,   584,  -333,    32],
       [  584, 10331, -1227,   658],
       [ -333, -1227,  2810,   -58],
       [   32,   658,   -58,   118]])

#### `array` operations

Mathematical symbols take on mathematical meanings in `numpy`, and so the `+` operator between two `np.array` just tries to add them together elementwise (it works differently to `list`-type objects). To concatenate you need a specific function.


In [8]:
# Numpy array addition: 
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print(a + b)  # Addition
print(np.concatenate([a,b]))  # Concatenation

[5 7 9]
[1 2 3 4 5 6]


### `pandas` (Panel Data Structures)

This is the module in Python for doing rectangular-data management, analysis and plotting. It provides tools to read and write external data.


In [9]:
import pandas as pd  # Usually imported with name "pd"

file_path = "https://raw.githubusercontent.com/barcelonagse-datascience/academic_files/master/data/tips.csv"
tips = pd.read_csv(file_path)  # read_csv allows importing .CSV files
print(tips.head(5))  # head gives first rows (arg = number of rows)

# Data formats in pandas
print(type(tips))
print(type(tips['tip']))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


There are the two basic data formats in `pandas`: `Series` and `DataFrame`. A `Series` is the equivalent to a vector in linear algebra. A `DataFrame` is the equivalent to a rectangular data structure. These types are equipped with several attributes useful for data management and analysis. In the tips example, the variable object `tips` is a `DataFrame`, while any individual column would be a `Series`.

---
## 7. Structured data operations (`pandas`)

### `Series`

They are accessed via their index, which is a label (a number or a string) for each entry. They are typically obtained by reading a dataset from an external file or when operating on a `DataFrame`, but they can be defined manually:

In [10]:
# Here no indices are specified (by default they are numerical)
a_series = pd.Series([1, 15, -5, None, 4, 123, 0, 78, 0, 1, -4])
a_series

0       1.0
1      15.0
2      -5.0
3       NaN
4       4.0
5     123.0
6       0.0
7      78.0
8       0.0
9       1.0
10     -4.0
dtype: float64

In [11]:
# Accessing a certain value via the index
a_series[0]

1.0

In [12]:
# .values returns a numpy.ndarray of the values
print(a_series.values)
# .index returns the index of the series in a object of index
print(type(a_series.index))

[  1.  15.  -5.  nan   4. 123.   0.  78.   0.   1.  -4.]
<class 'pandas.core.indexes.range.RangeIndex'>


In [13]:
# You can overwrite the index directly: 
a_series.index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]
# .index.values returns the index of the series in a numpy array
a_series.index.values

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'],
      dtype=object)

Accessing values via the index can be very useful, but sometimes you want to access the values by their order in the series as if it was a Python list. In other words "I want the first value!", without having to know the name of the label. This can be achieved with `.iloc`:


In [14]:
a_series.iloc[0], a_series["a"], a_series.iloc[-1]


(1.0, 1.0, -4.0)

In [15]:
# This just resets the index to default values
a_series = a_series.reset_index(drop = True)

# now if I sort the values from smaller to greater:
x = a_series.sort_values()
print(x)
x[0], x.iloc[0] 
# the indices remain, so x indexed by 0 is 1
# the ordering changes, so the first element of x is -5.0, the minimum

2      -5.0
10     -4.0
6       0.0
8       0.0
0       1.0
9       1.0
4       4.0
1      15.0
7      78.0
5     123.0
3       NaN
dtype: float64


(1.0, -5.0)

As usual one should explore the attributes of any python object one ends up working with. We have already accessed the `.index` and `.value`. Some other that are worth highlighting:

*   `.map`
*   `.corr`
*   `.describe`
*   `.hist`
*   `.plot`
*   `.size`
*   `.value_counts`
*   `.sort_values`

For example:

In [16]:
a_series.describe()

count     10.000000
mean      21.300000
std       43.410316
min       -5.000000
25%        0.000000
50%        1.000000
75%       12.250000
max      123.000000
dtype: float64

### Operations with `Series`

`Series` are `numpy` arrays behind the scenes, so we can compute element-wise functions on one series or several series at the same time. The result is another series with data type depending on the type of operations performed.


In [17]:
series1 = pd.Series([1, 3, 5, 7])
series2 = pd.Series([0, 10, -1, 6])

series3 = 2 * series1 + abs(series2)
series4 = series1 > series2 

print(series3)
print(series4)
# Take a look at the different Series objects!

0     2
1    16
2    11
3    20
dtype: int64
0     True
1    False
2     True
3     True
dtype: bool


What goes on in the previous examples is more subtle than it looks. How does Python know which elements from each series to join in the required operation together? What happens is that the indices happened to be the same. So when we ask something like

`series3 = series1 + series2`,

Python looks for entries in each series with the same index and then does an elementwise summation that it stores in a like-wise index in Series 3.

Consider instead the following example:


In [18]:
series1 = pd.Series([1, 10], index=["A", "B"])
series2 = pd.Series([4, -1], index=["C", "D"])
series3 = series1 + series2
print(series3)

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64


This aspect makes it very easy to work with series that we have sorted or manipulated otherwise; there is always the address to access a value. This helps prevent accidentally combining values we didn't mean to combine!

In [19]:
# accessing by list of index labels
a_series.index = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"]
x = a_series[["A", "K"]]

In [20]:
a_series

A      1.0
B     15.0
C     -5.0
D      NaN
E      4.0
F    123.0
G      0.0
H     78.0
I      0.0
J      1.0
K     -4.0
dtype: float64

In [21]:
x

A    1.0
K   -4.0
dtype: float64

In [22]:
# Getting a boolean-valued series by checking a condition
choose = (a_series == 0.0)
choose

A    False
B    False
C    False
D    False
E    False
F    False
G     True
H    False
I     True
J    False
K    False
dtype: bool

In [23]:
# Notice the index of x is a SUBSET of the index of "a_series"
# This can be useful when needing to relate values back to the original "a_series"!
x = a_series[choose]
print(x)
# or the complement
a_series[~choose]

G    0.0
I    0.0
dtype: float64


A      1.0
B     15.0
C     -5.0
D      NaN
E      4.0
F    123.0
H     78.0
J      1.0
K     -4.0
dtype: float64

We often use boolean masks to filter data in Pandas. We also get special boolean algebra operators to use in `numpy`/`pandas`, distinct from the and/or/not you will use in regular Python: `&` (AND), `|` (OR), `~` (NOT).


### Missing values

A series object in `pandas` can help us deal with missing data. We already see very naturally how data management can quickly lead to missing data.

In [24]:
series3 = series1 + series2
print(series3)

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64


What happened there is that in the operation labels could not be matched, so `pandas` tried to sum a numeric value with missing value, the result of which is a missing value.
The way to manually specify in `pandas` that a value is missing is to use `None`, as below:

In [25]:
temp = pd.Series([1, None, 2])
print(temp)

0    1.0
1    NaN
2    2.0
dtype: float64


`pandas` coerces `None` values to `NaN` ("Not a Number") values. We can create boolean masks on the basis of such values. The way to identify NaN or None values in a Series is to use either of the equivalent two attributes: `.isna()` and `.isnull()` (existing the opposite `.notna()` and `.notnull()`).

In [26]:
print(temp.isna())
print(temp.isnull())

0    False
1     True
2    False
dtype: bool
0    False
1     True
2    False
dtype: bool


In [27]:
temp.notna()
temp.notnull()

0     True
1    False
2     True
dtype: bool

### `DataFrame`

This is `pandas` model for rectangular data. Operationally similar to a dictionary of `Series`; each column of the `DataFrame` is a `Series` object, and comes with all the attributes/methods of a `Series`. An implication is that within each column the data type is common; across columns this can change.

In [28]:
# Recall our "tips" dataset
tips.head(5)  # The first method of our DataFrame object

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
# the other important attribute: name of rows and columns
print(tips.shape)
print(tips.index)
print(tips.columns)

(244, 7)
RangeIndex(start=0, stop=244, step=1)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


To access the columns of a `DataFrame` there are two standard ways.

In [30]:
tips.tip  # As if it were a method (NOT recommended)
tips["size"]  # As if it were a named index (RECOMMENDED)

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

The latter is recommended because, for example, the column `size` cannot be accessed via the first option (it would be confused with the method `.size`). The result of this operation is an object of type `Series`.

We can access various columns at a time, supplying a list of columns, obtaining a dataframe with the same index as the original and columns the chosen subset.

In [31]:
tips[["tip", "size", "sex"]].head(5)

tip  size     sex
0  1.01     2  Female
1  1.66     3    Male
2  3.50     3    Male
3  3.31     2    Male
4  3.61     4  Female

Similarly, you can access rows instead of columns with the same philosophy.

*   Using a list of index labels: `tips.loc[ [index1, index2, ...] ]`
*   Using a list of integer index location (i-loc): `tips.iloc[ [integer1, integer2, ...] ]`



In [32]:
# Accessing rows AND columns!
# Example of 2-dimension loc
tips.loc[[1, 3], ['sex', 'smoker']]

sex smoker
1  Male     No
3  Male     No

In [33]:
# Accessing rows AND columns!
# Example of 2-dimensional iloc
tips.iloc[[1, 3], 2:5]

sex smoker  day
1  Male     No  Sun
3  Male     No  Sun

Note that certain operations are exchangeable: the 3rd element of column "sex" can be obtained with either of the following ways:

In [34]:
tips.sex[2]  # Access col as series, then the 3rd element of that
tips.loc[2, "sex"]  # Access the entry in DF by giving the index labels of row and col
tips.loc[2]["sex"]  # Accessing the whole row as a series, then using the column name as index label

'Male'

As with `Series`, we can use a boolean-valued series to index a `DataFrame` provided that they share the same index labels. The simplest instance of this is to use series produced as boolean masks of columns of the dataframe. The output of this *filtering* operation is a dataframe with subset of rows corresponding to the `True` values in the boolean mask.

In [35]:
# Creates a boolean series with the same index labels as the data frame tips
tips['sex'] == "Male"

0      False
1       True
2       True
3       True
4      False
       ...  
239     True
240    False
241     True
242     True
243    False
Name: sex, Length: 244, dtype: bool

In [36]:
tips[tips['sex'] == "Male"].head(5)

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2

In [37]:
tips[(tips['sex'] == "Male") & (tips['day'] == "Sun")].head(5)  # Multiple booleans ("&", "|", "~")

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2

A `DataFrame` comes with several attributes for computing column-wise statistics and summaries. We highlight some of them:

*   `.boxplot` (check out the `by = ` option)
*   `.corr` and `.corrwith` (within and across `DataFrame`'s)
*   `.dot`
*   `.mean/median/max/quantile/sum`, etc.
*   `.sample`
*   `.sort_values`
*   `.unique`


### `GroupBy`

This `DataFrame` method groups the `DataFrame` according to the values of a column, treating them as categorical values. It returns a groupby object.

In [38]:
# Group tips DataFrame by size of table
by_size = tips.groupby("size")
print(by_size)

# If we coerce it to a list, we see something interesting: 
# it's basically a list of tuples
# The first element is the "category" variable, the second
# is a datafame. 
list(by_size)

[(1,      total_bill   tip     sex smoker   day    time  size
  67         3.07  1.00  Female    Yes   Sat  Dinner     1
  82        10.07  1.83  Female     No  Thur   Lunch     1
  111        7.25  1.00  Female     No   Sat  Dinner     1
  222        8.58  1.92    Male    Yes   Fri   Lunch     1),
 (2,      total_bill   tip     sex smoker   day    time  size
  0         16.99  1.01  Female     No   Sun  Dinner     2
  3         23.68  3.31    Male     No   Sun  Dinner     2
  6          8.77  2.00    Male     No   Sun  Dinner     2
  8         15.04  1.96    Male     No   Sun  Dinner     2
  9         14.78  3.23    Male     No   Sun  Dinner     2
  ..          ...   ...     ...    ...   ...     ...   ...
  237       32.83  1.17    Male    Yes   Sat  Dinner     2
  240       27.18  2.00  Female    Yes   Sat  Dinner     2
  241       22.67  2.00    Male    Yes   Sat  Dinner     2
  242       17.82  1.75    Male     No   Sat  Dinner     2
  243       18.78  3.00  Female     No  Thur  Di

In [39]:
list(tips.groupby("sex"))

[('Female',      total_bill   tip     sex smoker   day    time  size
  0         16.99  1.01  Female     No   Sun  Dinner     2
  4         24.59  3.61  Female     No   Sun  Dinner     4
  11        35.26  5.00  Female     No   Sun  Dinner     4
  14        14.83  3.02  Female     No   Sun  Dinner     2
  16        10.33  1.67  Female     No   Sun  Dinner     3
  ..          ...   ...     ...    ...   ...     ...   ...
  226       10.09  2.00  Female    Yes   Fri   Lunch     2
  229       22.12  2.88  Female    Yes   Sat  Dinner     2
  238       35.83  4.67  Female     No   Sat  Dinner     3
  240       27.18  2.00  Female    Yes   Sat  Dinner     2
  243       18.78  3.00  Female     No  Thur  Dinner     2
  
  [87 rows x 7 columns]),
 ('Male',      total_bill   tip   sex smoker  day    time  size
  1         10.34  1.66  Male     No  Sun  Dinner     3
  2         21.01  3.50  Male     No  Sun  Dinner     3
  3         23.68  3.31  Male     No  Sun  Dinner     2
  5         25.29  4.

In [40]:
# We can iterate through the groupby just like we would though a list of tuples!
for sex, data in tips.groupby("sex"):
    print(sex)
    print(data.mean())


Female
total_bill    18.056897
tip            2.833448
size           2.459770
dtype: float64
Male
total_bill    20.744076
tip            3.089618
size           2.630573
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.


We `groupby` to perform *some* operation on each group, to *map* over the groups, applying a function to each element. Very often this function is itself an aggregation (*reduction*). We want to somehow aggregate each group into a value or set of values that *describe* it.

To apply functions to each element of a `groupby`, we use `.apply`:


In [41]:
# Get the maximum bill by gender: 
def max_bill(df):
    return df['total_bill'].max()

tips.groupby("sex").apply(max_bill)

sex
Female    44.30
Male      50.81
dtype: float64

Many aggregation functions that exist on Series and `DataFrames` (`mean`, `max`, `min`, etc.) can be called directly via the groupby object:

In [42]:
print(tips.groupby("sex").max())
print(tips.groupby("sex").mean())

        total_bill   tip smoker   day   time  size
sex                                               
Female       44.30   6.5    Yes  Thur  Lunch     6
Male         50.81  10.0    Yes  Thur  Lunch     6
        total_bill       tip      size
sex                                   
Female   18.056897  2.833448  2.459770
Male     20.744076  3.089618  2.630573


We can actually `groupby` more than one column:

In [43]:
tips.groupby(["sex", "day"])['tip'].mean()

sex     day 
Female  Fri     2.781111
        Sat     2.801786
        Sun     3.367222
        Thur    2.575625
Male    Fri     2.693000
        Sat     3.083898
        Sun     3.220345
        Thur    2.980333
Name: tip, dtype: float64

### Combining DataFrames

There are many ways to combine various `DataFrame`s into a new one, extending in many ways what we already saw for operations on `Series`. The main ways of doing this are:

*   **Concatenate**: paste row-column-wise and taking action on `NaN`s (this works more on the rectangular structure of the data)
*   **Merge**: combine `DataFrame`s using a common piece of information, e.g. an identifier column (this works more as a database operation)



**Concatenate**

In [44]:
# Concatenate
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "C": pd.Series([7])})
pd.concat([df1, df2], axis = 0)
# axis: 0 for pasting below, 1 for pasting on the side

A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  6.0  NaN
0  4  NaN  7.0

Concatenation is mostly used when the rows index or columns index is shared.  
For example, you might have data with the same columns and want to concatenate them on axis 0:

In [45]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "B": pd.Series([7])})
df3 = pd.concat([df1, df2], axis = 0)
df3

A  B
0  1  4
1  2  5
2  3  6
0  4  7

Note what happened to the index of our concatenated dataframe above: we might want to reset it.

In [46]:
df3.reset_index()

index  A  B
0      0  1  4
1      1  2  5
2      2  3  6
3      0  4  7

Similarly, you might have data with the same rows and different columns:

In [47]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"C": pd.Series([4,5,8]), "D": pd.Series([7,12,1])})
pd.concat([df1, df2], axis = 1)

A  B  C   D
0  1  4  4   7
1  2  5  5  12
2  3  6  8   1

Note what happens if the rows do not align, and you concatenate on axis 1 (by rows):

In [48]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"C": pd.Series([7]), "D": pd.Series([10])})
pd.concat([df1, df2], axis = 1)

A  B    C     D
0  1  4  7.0  10.0
1  2  5  NaN   NaN
2  3  6  NaN   NaN

Taking action on `NaN`s that may appear as a results of `concat` is done by specifying the `join` argument to `inner` or `outer` (defaults to `outer`).

In [49]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([4]), "C": pd.Series([7])})
print(pd.concat([df1, df2], axis = 1, join = "outer"))  # "outer" join
print(pd.concat([df1, df2], axis = 1, join = "inner"))  # "inner" join

   A  B    A    C
0  1  4  4.0  7.0
1  2  5  NaN  NaN
2  3  6  NaN  NaN
   A  B  A  C
0  1  4  4  7


**Merge**

`merge` is commonly used when your two `DataFrame`s are connected but do not share an index or columns. With merge we will connect two `DataFrame`s on some common piece of information, e.g. a common column. To tell `merge` what to with `NaN`s we specify a type of `join`, just as with `concat`. There are four types of `join` operations:

*   `inner`-join: **intersection** of *keys*
*   `outer`-join: **union** of *keys*
*   `left`-join: use *keys* from **left only**
*   `right`-join: use *keys* from **right only**

In [50]:
df1 = pd.DataFrame({"A": pd.Series([1, 2, 3]), "B": pd.Series([4, 5, 6])})
df2 = pd.DataFrame({"A": pd.Series([3, 4]), "C": pd.Series([7, 8])})
print(df1)
print('\n')
print(df2)

   A  B
0  1  4
1  2  5
2  3  6


   A  C
0  3  7
1  4  8


In [51]:
# Merging, "on" defines on what piece of information the DataFrame's will merge
pd.merge(df1, df2, on = 'A', how = 'right')  # if column names differ, use "left_on" and "right_on"

A    B  C
0  3  6.0  7
1  4  NaN  8

In [52]:
pd.merge(df1, df2, on = 'A', how = 'left')

A  B    C
0  1  4  NaN
1  2  5  NaN
2  3  6  7.0

In [53]:
pd.merge(df1, df2, on = 'A', how = 'outer')

A    B    C
0  1  4.0  NaN
1  2  5.0  NaN
2  3  6.0  7.0
3  4  NaN  8.0

In [54]:
pd.merge(df1, df2, on='A', how = 'inner')

A  B  C
0  3  6  7

Note that when merging on columns, the DataFrame indexes will be ignored and new index is created.

---
## String manipulation

### Simple operations

You may find yourself working with text data, a.k.a. strings. 

Strings are actually iterables, just like lists. They can be subset analogously:

In [55]:
x = "one python string"
x[4:10]

'python'

In [56]:
# You can also turn a string into a list of strings via the "split" method:
x = "one python string"
y = x.split(" ")
y == ["one", "python", "string"]

True

In [57]:
# The reverse is also possible via the "join" method:
space = " "
z = space.join(y)
z == x

True

You can also make everything lower (or upper) case, replace certain substrings with other substrings, and check for the existence of a substring with `in`:

In [58]:
z = "My Python String"
z.lower()

'my python string'

In [59]:
z.upper()

'MY PYTHON STRING'

In [60]:
w = z.replace("Python", "R")
print(w)
"Python" in w

My R String


False

There are many more easy-to-use, built-in tools for working with text data in Python. You can read more here:

*   https://docs.python.org/3/library/stdtypes.html#string-method

### Regular expressions

A *regular expression* is a special sequence of characters that helps you match or find other strings or sets of strings, using a specialized syntax held in a pattern. Python uses the module `re` to deal with them.

Let's pretend we have an `html` text. Find **all** words tagged as bold (`<b>word</b>`) in `html`, turn them to italics (`<i>word</i>`) and add the word "freaking" before them.

In [61]:
import re

a_text = 'Why am I taking this <b>course</b>? I want to go back to the <b>holidays</b>.'

# Preffix 'r' is an indicator of regular expression
the_regex = r'<b>([a-z\s]+)</b>'
replacement = r'<i>freaking \1</i>' #\1 is for group 1, we are asking to replace by the matched string

# Function to replace a regular expression with another
re.sub(the_regex, replacement, a_text)

'Why am I taking this <i>freaking course</i>? I want to go back to the <i>freaking holidays</i>.'

Some helpful functions to manouvering with regular expressions with `re`:

*  `re.search(pattern, string)`: scan through `string` looking for locations where the regular expression `pattern` produces a match, and return a corresponding match object.
*  `re.match(pattern, string)`: if zero or more characters at the beginning of `string` match the regular expression `pattern`, return a corresponding match object.
*  `re.split(pattern, string)`: split `string` by the occurrences of `pattern`
*  `re.sub(pattern, repl, string)`: return the `string `obtained by replacing the leftmost non-overlapping occurrences of `pattern` in string by the replacement `repl`
*  `re.findall()`: search for *all* occurrences that match a given pattern

Regular expressions are relatively complex and there is a long list of combinations we can make, which are well outside the scope of this introduction. We limit to mentioning some special characters to form regular expressions:

*  `^`: Start of string
*  `$`: End of string
*  `.`: One character, no matter which (except line break)
*  `*`: match 0 or more repetitions of the preceding RE
*  `+`: match 1 or more repetitions of the preceding RE
*  `?`: match 0 or 1 repetition of the preceding RE
*  `{m,n}`: Causes the resulting RE to match from m to n repetitions of the preceding RE. The comma and the n are optional depending on the case
*  `|`: OR. E.g. A|B means match RE A or B
*  `(...)`: Matches whatever regular expression is inside the parentheses
*  `[]`: Defines a subset of characters to match
*  `\`: Either escapes special characters (permitting you to match characters like '*', '?', and so forth), or signals a special sequence (e.g. \s means a white space).
*  `\w`: Matches a word (letters only)
*  `\W`: Matches a word (letters and characters, equivalent to `[^a-zA-Z0-9_]`)

---
## Some advanced concepts


### Copy vs. assignment

Look at the following example:

In [62]:
a = [1, 2, 5]
b = a
b[2] = 10

In [63]:
print(a)
print(b)

[1, 2, 10]
[1, 2, 10]


What happens is that really `a` and `b` point to the same place in the memory and share the same data.

In [64]:
print(id(a))
print(id(b))

140330868914928
140330868914928


The way to create an object that will *copy* the data in a but not *share* the data with a is to use the method `copy()`.

In [65]:
a = [1, 2, 5]
b = a.copy()
print(id(a))
print(id(b))

140330869489168
140330876734912


In [66]:
b[2] = 10
print(a)
print(b)

[1, 2, 5]
[1, 2, 10]


This goes a bit deeper into the concept how `python` uses memory in your computer, but it is important to have a grasp on it in order to avoid potential problems when memory becomes an issue.

Note that the behaviour we observed above for lists would not be the same for integers. For example:

In [67]:
a = 2
b = a
a += 1
print(a)
print(b)
print(id(a))
print(id(b))

3
2
11126752
11126720


Things also become a little trickier when you deal with lists of lists. 

In [68]:
a = [1, [2, 3], 5, 'abc'] 
b = a.copy()
b[1].append(100)

In [69]:
print(a)
print(b)

[1, [2, 3, 100], 5, 'abc']
[1, [2, 3, 100], 5, 'abc']


In [70]:
print(id(a))
print(id(b))

140330869489168
140330868573760


What happened here is that both `a` and `b` still point to some deeper list `[2, 3]`. For this reason there is also the `deepcopy`.

In [71]:
# Try now 
from copy import deepcopy
a = [1, [2, 3], 5, 'abc'] 
b = deepcopy(a)
b[1].append(100)
print(a)
print(b)

[1, [2, 3], 5, 'abc']
[1, [2, 3, 100], 5, 'abc']


In [72]:
print(id(a))
print(id(b))

140330869430704
140330978455712


Be careful when you write statements such as `name1 = name2`.

### Default values in functions

In `python` we get to assign default values to inputs of functions. For example:

In [73]:
# New function "f"
def f(a = 1, b = 2):
    return a + b


In [74]:
# Function "f" can be validly be called in the following ways
print(f())
print(f(10))
print(f(b = 4))
print(f(10, 4))
print(f(a = 10, b = 4))
print(f(b = 4, a = 10))

3
12
5
14
14
14


In [75]:
# But NOT like this
f(a = 10, 4)

SyntaxError: ignored

In [77]:
# however this works
f(10, b = 4)

14

You cannot omit an argument name, if you stated previous arguments names.

---
## Particular topics

### Date and time objects

We introduce how to deal with time and date type of objects in Python. To do this, we need a module denominated `datetime`, which contains the class `datetime`.

In [78]:
from datetime import datetime  # This is a module and a class

# Current date
current_time = datetime.now()
print(current_time)
print(type(current_time))

2022-10-26 18:30:10.282871
<class 'datetime.datetime'>


`current_time` is of class `datetime`, but this is just one of five distinct time-object classes:

*   `datetime`: allows to work with times and dates together (month, day, year, hour, second, microsecond).
*   `date`: works with dates only (month, day, year), independent of time. 
*   `time`: works with time only (hour, minute, second, microsecond), independent of date. 
*   `timedelta`: a duration of time used for measuring distance between to time points.

The most common scenario with time data is translating from and to regular character objects, which is the most frequent format that we will encounter when importing times and dates. We use the following two functions:

In [79]:
today_date = '2022-01-04'

# Create date object in given time format yyyy-mm-dd
today_date = datetime.strptime(today_date, '%Y-%m-%d')

print(today_date)
print(type(today_date))

2022-01-04 00:00:00
<class 'datetime.datetime'>


Note we used the *pattern* `%Y-%m-%d` to indicate the year-month-day format we want to give the date object. A full list of imaginable patterns can be found in the library's [documentation](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior).

In [80]:
print('* Month:', today_date.month)  # Get month from date
print('* Year:', today_date.year)  # Get month from year
print('* Day of month:', today_date.day)  # ...
print('* Day of Week (number):', today_date.weekday())  # Recall indexing

* Month: 1
* Year: 2022
* Day of month: 4
* Day of Week (number): 1


In [81]:
print('* Hour: ', current_time.hour)
print('* Minute: ', current_time.minute)
print(current_time.isocalendar())  # Returns (year, # week, # day)

* Hour:  18
* Minute:  30
(2022, 43, 3)


As mentioned, you can convert from time to string with the function `strftime()`. With the argument `format`, you can change the date format in the resulting string.

In [82]:
today_str = datetime.strftime(today_date, format = '%d-%m-%Y')
type(today_str)
print(today_str)

04-01-2022


Recall we mentioned that to measure time spans, or to operate dates or times (add/subtract) we could use the `timedelta` type of object. Mind you, these objects need not be anchored on a specific date and they can be a generic time frame.

In [83]:
from datetime import timedelta

# timedelta objects
three_weeks = timedelta(weeks = 3)
one_year = timedelta(days = 365)

print(three_weeks)
print(type(three_weeks))
print(three_weeks.days)
print(one_year.days)

21 days, 0:00:00
<class 'datetime.timedelta'>
21
365


Let us now operate on these objects.

In [84]:
from datetime import datetime, timedelta

# Current time
now = datetime.now()
print("Today's date: ", str(now))

# Add three weeks to current date
now_in_3weeks = now + three_weeks
print('Date after three weeks: ', now_in_3weeks)

# Subtract one year from current date
one_year_ago = now - one_year
print('Date one year ago: ', one_year_ago)
print(type(one_year_ago))

Today's date:  2022-10-26 18:30:10.371885
Date after three weeks:  2022-11-16 18:30:10.371885
Date one year ago:  2021-10-26 18:30:10.371885
<class 'datetime.datetime'>


In [85]:
from datetime import date

# Create two dates
date1 = date(2011, 5, 28)
date2 = date(2015, 6, 6)
# create two dates with year, month, day, hour, minute, and second
date1b = datetime(2011, 5, 28, 23, 1, 0)
date2b = datetime(2015, 6, 6, 22, 52, 10)

# Difference between two dates
date_diff = date2 - date1
date_diffb = date2b - date1b
print("Time difference (days): ", date_diff.days)
print("Time difference: ", date_diffb)
print(type(date_diff))

Time difference (days):  1470
Time difference:  1469 days, 23:51:10
<class 'datetime.timedelta'>


In [86]:
# To work with time zones:
from pytz import timezone

# Create timezone US/Eastern
est = timezone('US/Eastern')

# Re-set date to local time
loc_time = est.localize(datetime(2015, 6, 6, 22, 52, 10))
print(loc_time)

2015-06-06 22:52:10-04:00


You can also work with time objects using `pandas`. You can convert text strings into `pandas` `Datetime` objects using:

*  `to_datetime()`: to convert string dates/times to `datetime` objects.
*  `to_timedelta()`: find differences in times.


In [87]:
import pandas as pd
import numpy as np

# String to datetime
good_date = pd.to_datetime("6th of June, 2015")
print(good_date)

# Create date series to_timedelta() (add numpy)
date_series = good_date + pd.to_timedelta(np.arange(12), 'D')
print(date_series)

# Create date series using date_range() function
date_series = pd.date_range('06/06/2015', periods = 12, freq = 'D')
print(date_series)

2015-06-06 00:00:00
DatetimeIndex(['2015-06-06', '2015-06-07', '2015-06-08', '2015-06-09',
               '2015-06-10', '2015-06-11', '2015-06-12', '2015-06-13',
               '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2015-06-06', '2015-06-07', '2015-06-08', '2015-06-09',
               '2015-06-10', '2015-06-11', '2015-06-12', '2015-06-13',
               '2015-06-14', '2015-06-15', '2015-06-16', '2015-06-17'],
              dtype='datetime64[ns]', freq='D')


In [88]:
# Create a DataFrame with date as a column
data = pd.DataFrame()
data['date'] = date_series
data.head()

date
0 2015-06-06
1 2015-06-07
2 2015-06-08
3 2015-06-09
4 2015-06-10

In [89]:
# .dt gives access to the series datetime properties if any
# Extract year, month, day, hour, and minute; and assign to new columns
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
data['day'] = data['date'].dt.day
data['hour'] = data['date'].dt.hour
data['minute'] = data['date'].dt.minute
data.head()

date  year  month  day  hour  minute
0 2015-06-06  2015      6    6     0       0
1 2015-06-07  2015      6    7     0       0
2 2015-06-08  2015      6    8     0       0
3 2015-06-09  2015      6    9     0       0
4 2015-06-10  2015      6   10     0       0

### Web scraping and `html` parsing

Web *scraping* deals with the retrieval of information featured in some web page. It basically consists of reading the content in a URL, and posteriorly *parsing* it to extract the relevant information that you are looking for. This is an extensive topic in itself so we will just introduce the plain basics to get you started.

Before anything, note that most information in a HTML source is of little use to us and is used to render and format the webpage itself. Therefore it would be wise to familiarise yourself with HTML tags as and when needed. We must consider some design aspects of creating a *spider* that will *crawl* the target webpage and get us the desired content.

1.   Identify tags that contain useful information
2.   Add randomised waiting periods between every access to website
3.   Make use of logs to monitor progress
4.   Regularly write collected data to an external file
5.   **Always** respect `robots.txt` file defined by websites

We use as an example Wikipedia in english. The target will be to  retrieve the summary of the featured article in Wikipedia along with all the URLs in it.

In [90]:
from bs4 import BeautifulSoup
#import urllib  # If you're using Python 2.x
import urllib.request  # If you're using Python 3

url = 'https://en.wikipedia.org/wiki/Main_Page'
#html = urllib.urlopen(url).read()  # Python 2.x
with urllib.request.urlopen(url) as url_content:
    html = url_content.read()

# BeautifulSoup() is a formatting module to interpret html/xml
soup = BeautifulSoup(html, 'html.parser')
print(soup)

<!DOCTYPE html>

<html class="client-nojs" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Wikipedia, the free encyclopedia</title>
<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"56f875a1-6427-4f07-ad9d-e5d9987ac99f","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Main_Page","wgTitle":"Main Page","wgCurRevisionId":1114291180,"wgRevisionId":1114291180,"wgArticleId":15580374,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Main_Page","wgRelevantArticleId":15580374,"wgIsProbablyEditable":fal

The `prettify` method turns your soup into a more nicely formatted string with a separate line for each tag and each string, and indented.

In [91]:
print(type(soup))
print(soup.prettify()[0:5000])

<class 'bs4.BeautifulSoup'>
<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Wikipedia, the free encyclopedia
  </title>
  <script>
   document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"56f875a1-6427-4f07-ad9d-e5d9987ac99f","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Main_Page","wgTitle":"Main Page","wgCurRevisionId":1114291180,"wgRevisionId":1114291180,"wgArticleId":15580374,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Main_Page","wgRelevantA

The text is structured with HTML tags organised in a systematic way. This structure is referred to as a *HTML DOM* (Document Object Model).

We are interested in grabbing the summary of the article of the day, from the Wikipedia main page along with all the links in it. So we'll use `BeautifulSoup`'s functions to parse HTML tags that contain this information or lead us to it in the form of embedded URLs.

On inspection of the HTML source we identify that the article summary is enclosed in the first `p` tag. `p` stands for paragraph. The idea is as follows,

1.   Using the function in `.find_all()` in BeautifulSoup we search for all tags of the type `p`
2.  Identify the correct paragraph and extract URLs.
3.  Extract text.



In [92]:
# 1. search for all tags of the type p
paragraphs_list = soup.find_all(name = "p")
paragraphs_list

[<p><i><b><a href="/wiki/Mischief_Makers" title="Mischief Makers">Mischief Makers</a></b></i> is a 1997 <a href="/wiki/Side-scrolling_video_game" title="Side-scrolling video game">side-scrolling</a> platform video game, the first for the <a href="/wiki/Nintendo_64" title="Nintendo 64">Nintendo 64</a> <i>(pictured)</i>, developed by <a href="/wiki/Treasure_(company)" title="Treasure (company)">Treasure</a> and published by <a href="/wiki/Enix" title="Enix">Enix</a> and <a href="/wiki/Nintendo" title="Nintendo">Nintendo</a>. The player assumes the role of Marina, a robot who grabs, shakes, and throws objects in her journey to rescue her creator from the planet's emperor. The game is presented in <a href="/wiki/2.5D" title="2.5D">2.5D</a>, with pre-rendered 3D backgrounds behind 2D gameplay. A 12-person team developed the game over two years as Treasure's first title for a Nintendo console. It was shown at the 1997 <a href="/wiki/E3" title="E3">Electronic Entertainment Expo</a> before its

In [93]:
# 2. Identify the correct paragraph
paragraph = soup.findAll(name = 'p')[0]
paragraph

<p><i><b><a href="/wiki/Mischief_Makers" title="Mischief Makers">Mischief Makers</a></b></i> is a 1997 <a href="/wiki/Side-scrolling_video_game" title="Side-scrolling video game">side-scrolling</a> platform video game, the first for the <a href="/wiki/Nintendo_64" title="Nintendo 64">Nintendo 64</a> <i>(pictured)</i>, developed by <a href="/wiki/Treasure_(company)" title="Treasure (company)">Treasure</a> and published by <a href="/wiki/Enix" title="Enix">Enix</a> and <a href="/wiki/Nintendo" title="Nintendo">Nintendo</a>. The player assumes the role of Marina, a robot who grabs, shakes, and throws objects in her journey to rescue her creator from the planet's emperor. The game is presented in <a href="/wiki/2.5D" title="2.5D">2.5D</a>, with pre-rendered 3D backgrounds behind 2D gameplay. A 12-person team developed the game over two years as Treasure's first title for a Nintendo console. It was shown at the 1997 <a href="/wiki/E3" title="E3">Electronic Entertainment Expo</a> before its 

In [94]:
# 2. Extract URLs
urls = [tag['href'] for tag in paragraph.findAll('a', href = True)]
for url in urls:
    print(url)

print('\n')

/wiki/Mischief_Makers
/wiki/Side-scrolling_video_game
/wiki/Nintendo_64
/wiki/Treasure_(company)
/wiki/Enix
/wiki/Nintendo
/wiki/2.5D
/wiki/E3
/wiki/Boss_(video_games)
/wiki/Replay_value
/wiki/Sound_bite
/wiki/Mischief_Makers




An HTML document is a collection of nodes with (or without) child nodes. To build the text of the article summary, we loop through all the children and concatenate the text.

In [95]:
# 3. Build the text of the article summary by looping through all the children and concatenating the text 
text = ''
for ch in paragraph.children:
    text = text + ch.string

print(text + '\n')

Mischief Makers is a 1997 side-scrolling platform video game, the first for the Nintendo 64 (pictured), developed by Treasure and published by Enix and Nintendo. The player assumes the role of Marina, a robot who grabs, shakes, and throws objects in her journey to rescue her creator from the planet's emperor. The game is presented in 2.5D, with pre-rendered 3D backgrounds behind 2D gameplay. A 12-person team developed the game over two years as Treasure's first title for a Nintendo console. It was shown at the 1997 Electronic Entertainment Expo before its release. Reviews were mixed, with praise for its inventiveness, personality, and boss fights, but criticism for its brevity, low difficulty, low replay value, sound, and harsh introductory learning curve. Retrospective reviewers disagreed with the originally poor reception, and several highlighted Marina's signature "Shake, shake!" sound bite. In 2009, GamesRadar called it "possibly the most underrated and widely ignored game on the N